cms/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.principal, name='principal'),
    path('froala_editor/', include('froala_editor.urls')),
    path('login/', include('login.urls', namespace='login')),
    path('administracion/', include('administracion.urls', namespace='administracion')),
    path('publicaciones/', include('publicaciones.urls', namespace='publicaciones')),
    path('kanban/', include('kanban.urls', namespace='kanban')),
    path('comentarios/', include('comentarios.urls', namespace='comentarios')),
    path('categoria/<int:categoria_id>/', views.publicaciones_categoria, name='publicaciones_categoria'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views

app_name = 'login'  

urlpatterns = [
    path('', views.inicio_sesion, name='inicio_sesion'),
    path('registro/', views.registro, name='registro'),
    path('cerrar-sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path('perfil/', views.perfil_usuario, name='perfil'),
    path('perfil/actualizar/', views.perfil_actualizar, name='perfil_actualizar'),
    path('perfil/cargar_imagen/', views.cargar_imagen, name='cargar_imagen'),
]

login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from roles.models import Rol

class Usuario(AbstractUser):
    """
    Modelo personalizado de usuario que extiende AbstractUser.
    
    Atributos:
        roles (ManyToManyField): Roles asignados al usuario.
        suscriptor (BooleanField): Indica si el usuario es suscriptor.
        rol_activo (ForeignKey): El rol activo seleccionado por el usuario.

    Métodos:
        __str__: Representación en cadena del usuario (nombre de usuario).
    """
    username = models.CharField(
        max_length=20,
        unique=True,
        help_text='Máximo 20 caracteres. Requerido. Letras, dígitos y @/./+/-/_ solamente.',
    )
    imagen = models.ImageField(upload_to='profile_images', blank=True, null=True)
    roles = models.ManyToManyField(Rol, related_name='usuarios')
    suscriptor = models.BooleanField(default=True)
    
    #def save(self, *args, **kwargs):
        # Eliminar todos los "@" de la cadena
        #self.username = self.username.replace('@', '')
        
        # Agregar "@" al principio
        #self.username = f'@{self.username}'
        
        #super(Usuario, self).save(*args, **kwargs)

    def __str__(self):
        return self.username
    

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django.core.exceptions import ValidationError

class FormularioRegistro(UserCreationForm):
    """
    Formulario de registro de usuarios con campos de username, email y contraseña.
    """
    email = forms.EmailField(label='Correo Electrónico', required=True)

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')
        labels = {
            'username': 'Usuario',
            'password1': 'Contraseña',
            'password2': 'Confirmar Contraseña'
        }

class FormularioActualizarPerfil(forms.ModelForm):
    """
    Formulario para la actualización del perfil de usuarios, incluyendo cambio de contraseña opcional.
    """
    contraseña_actual = forms.CharField(
        label='Contraseña Actual',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña Actual'}),
        required=True
    )
    nueva_contraseña1 = forms.CharField(
        label='Nueva Contraseña',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Nueva Contraseña'}),
        required=False
    )
    nueva_contraseña2 = forms.CharField(
        label='Confirmar Nueva Contraseña',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirmar Nueva Contraseña'}),
        required=False
    )
    
    class Meta:
        model = Usuario
        fields = ('username', 'email')
        labels = {
            'username': 'Usuario',
            'email': 'Correo Electrónico'
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import FormularioRegistro, FormularioActualizarPerfil
from publicaciones.models import Publicacion_solo_text
from django.urls import reverse
from django.http import JsonResponse

def inicio_sesion(request):
    """
    Vista para iniciar sesión de un usuario.

    Esta vista permite al usuario ingresar sus credenciales para iniciar sesión en el sistema.

    Parámetros:
        request: La solicitud HTTP entrante.

    Retorna:
        Redirecciona a la vista de perfil del usuario si el inicio de sesión es exitoso, 
        o muestra la página de inicio de sesión con mensajes de error.

    """
    redirect_url = None  # Variable para almacenar la URL de redirec
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            nombre_usuario = formulario.cleaned_data.get('username')
            contraseña = formulario.cleaned_data.get('password')
            usuario = authenticate(username=nombre_usuario, password=contraseña)
            if usuario is not None:
                login(request, usuario)
                return redirect('/')
            else:
                messages.error(request, 'Credenciales inválidas. Por favor, inténtalo de nuevo.')
                redirect_url = request.path
        else:
            messages.error(request, 'Por favor, corrige los errores a continuación.')
            redirect_url = request.path
    else:
        formulario = AuthenticationForm()
    
    contexto = {'formulario': formulario,
                'redirect_url': redirect_url}
    return render(request, 'login/inicio_sesion.html', contexto)

def registro(request):
    """
    Vista para registrar un nuevo usuario.

    Esta vista permite al usuario registrar una nueva cuenta proporcionando la información requerida.

    Parámetros:
        request: La solicitud HTTP entrante.

    Retorna:
        Redirecciona a la página de inicio de sesión después de un registro exitoso,
        o muestra la página de registro con mensajes de error.

    """
    redirect_url = None  # Variable para almacenar la URL de redirección
    if request.method == 'POST':
        formulario = FormularioRegistro(request.POST)
        if formulario.is_valid():
            formulario.save()
            nombre_usuario = formulario.cleaned_data.get('username')
            contraseña = formulario.cleaned_data.get('password1')
            usuario = authenticate(username=nombre_usuario, password=contraseña)
            login(request, usuario)
            messages.success(request, 'Registro exitoso.')
            redirect_url=reverse('login:inicio_sesion')
            
        else:
            messages.error(request, 'Por favor, corrige los errores a continuación.')
            redirect_url = request.path
    else:
        formulario = FormularioRegistro()
    
    contexto = {'formulario': formulario,'redirect_url': redirect_url}

    return render(request, 'login/registro.html', contexto)

@login_required
def cerrar_sesion(request):
    """
    Vista para cerrar la sesión de un usuario.

    Esta vista cierra la sesión del usuario, vacía el campo 'rol_activado'
    y lo redirecciona a la página de inicio de sesión.

    Parámetros:
        request: La solicitud HTTP entrante.

    Retorna:
        Redirecciona a la página de inicio de sesión.

    """
    logout(request)
    return redirect('/')

@login_required
def perfil_usuario(request):
    """
    Vista para mostrar el perfil del usuario.
    Esta vista muestra el perfil del usuario, incluidos sus roles activos y la posibilidad de activar un rol adicional.
    Si el usuario no tiene roles, se muestra un mensaje correspondiente.
    Parámetros:
    request: La solicitud HTTP entrante.
    Retorna:
    Renderiza la plantilla de perfil con la información del usuario.
    """
    usuario = request.user

    # Obtener roles del usuario
    roles = usuario.roles.all()
    mensaje_roles = 'No cuenta con ningún rol asignado.'
    
    # Si el usuario tiene roles, no mostramos el mensaje
    if roles:
        mensaje_roles = None

    
    publicaciones = Publicacion_solo_text.objects.filter(autor=usuario)
    
    contexto = {
        'usuario': usuario,
        'roles': roles,
        'mensaje_roles': mensaje_roles,
        'publicaciones':publicaciones
    }
    
    return render(request, 'login/perfil_usuario.html', contexto)

@login_required
def perfil_actualizar(request):
    """
    Vista para actualizar el perfil del usuario.

    Esta vista permite al usuario actualizar su perfil, incluida la información y la contraseña.

    Parámetros:
        request: La solicitud HTTP entrante.

    Retorna:
        Redirecciona a la vista 'perfil_usuario' después de actualizar el perfil.
    """
    usuario = request.user
    redirect_url = None
    if request.method == 'POST':
        formulario = FormularioActualizarPerfil(request.POST, instance=usuario)
        if formulario.is_valid():
            contraseña_actual = formulario.cleaned_data.get('contraseña_actual')
            if contraseña_actual and not usuario.check_password(contraseña_actual):
                messages.error(request, 'La contraseña actual no es correcta.')
                redirect_url=request.path
            else:
                nueva_contraseña1 = formulario.cleaned_data.get('nueva_contraseña1')
                nueva_contraseña2 = formulario.cleaned_data.get('nueva_contraseña2')
                if nueva_contraseña1 and nueva_contraseña1 == nueva_contraseña2:
                    usuario.set_password(nueva_contraseña1)
                formulario.save()
                messages.success(request, 'Perfil actualizado exitosamente.')
                redirect_url = reverse('login:perfil')
    else:
        formulario = FormularioActualizarPerfil(instance=usuario)
    contexto = {
        'form': formulario,
        'usuario': usuario,
        'redirect_url': redirect_url
    }

    return render(request, 'login/perfil_actualizar.html', contexto)

@login_required
def cargar_imagen(request):
    """
    Vista que permite a un usuario autenticado cargar una imagen de perfil.

    El usuario envía la imagen mediante una petición POST. Si la carga es exitosa, 
    la vista devuelve la URL de la imagen cargada. En caso contrario, devuelve un mensaje de error.

    Args:
        request (HttpRequest): Objeto de solicitud HTTP.

    Returns:
        JsonResponse: 
            - Si la imagen se carga con éxito: {'url': <URL_de_la_imagen>}.
            - Si hay un error o no se envió una imagen: {'error': 'No se pudo cargar la imagen'}.

    Note:
        Se espera que el modelo del usuario tenga un campo llamado 'imagen' donde se almacenará 
        la imagen cargada. La vista requiere que el usuario esté autenticado para poder cargar una imagen.
    """
    
    usuario = request.user

    if request.method == 'POST' and 'imagen' in request.FILES:
        usuario.imagen = request.FILES['imagen']
        usuario.save()
        return JsonResponse({'url': usuario.imagen.url})

    return JsonResponse({'error': 'No se pudo cargar la imagen'})

templates/login/inicio_sesion.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <!-- Enlaces para los íconos de favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon_io/site.webmanifest' %}">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Inicio de Sesión</title>
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
    <!-- Custom styles for full-height container -->
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: black;
            margin: 0;
            padding: 0;
        }

        .row.justify-content-center {
            height: 100vh;
            /* Establece la altura al 100% del viewport (pantalla) */
        }

        .col-xl-12 {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100%;
            /* Establece la altura al 100% del viewport (pantalla) */
        }

        /* Cambios para el fondo y color del texto en la parte del login */
        .col-lg-3 {
            background-color: #000;
            color: #000;
            /* Color del texto en negro */
        }

        /* Resto de tus estilos CSS existentes */
    </style>
</head>

<body>
    {% include 'mensajes.html' %}
    <div class="row justify-content-center">
        <!--Estos 2 divs componen la logica para que se reproduzca video en vez de la imagen-->
        <!--Si quieres volver a la imagen, elimina los 2 div-->
        <!--Y agrega-->
        <!--
        <div class="col-lg-9 d-none d-lg-block bg-login-image"></div>
        <div class="col-lg-3">
        -->
        <div class="col-lg-9 d-none d-lg-block bg-login-video">
            <video autoplay loop muted playsinline>
                <source src="{% static 'videos/background-video.mp4' %}" type="video/mp4">
                <!-- Agrega formatos de video adicionales aquí, como WebM y Ogg, si es necesario -->
            </video>
        </div>
        <div class="col-lg-3 offset-lg-9">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h5 text-gray-100 mb-4">CMS</h1>
                </div>

                <form method="post" class="user">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="username" placeholder="Usuario">
                        {% if formulario.username.errors %}
                        <ul class="errorlist">
                            {% for error in formulario.username.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <input type="password" class="form-control" name="password" placeholder="Contraseña">
                        {% if formulario.password.errors %}
                        <ul class="errorlist">
                            {% for error in formulario.password.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>

                    <button type="submit" class="btn btn-primary btn-block">Iniciar Sesión</button>
                </form>

                <hr>
                <div class="text-center">
                    <a href="{% url 'login:registro' %}">Regístrate aquí</a>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/login/perfil_actualizar.html
{% extends 'base.html' %}
{% block title %}Actualizar Perfil{% endblock %}

{% block content %}
<style>
  .container {
      max-width: 600px;
      margin: 0 auto;
      /* Centra el contenido horizontalmente */
      padding: 20px;
  }
</style>

<div class="container">
  <br>
  <h2>Actualizar Perfil</h2>
  <br><br>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <br><br>
    <button class="btn btn-primary" type="submit">Actualizar</button>
    <a href="{% url 'login:perfil' %}" class="btn btn-secondary">Cancelar</a>
  </form>
</div>
{% endblock %}

templates/login/perfil_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Perfil de {{ usuario.username }}{% endblock %}

{% block content %}
<link href="{% static 'css/perfil_usuario.css' %}" rel="stylesheet" />

<div class="profile-container">
  <div class="profile-image">
    {% if usuario.imagen %}
    <img id="imagen-de-perfil" src="{{ usuario.imagen.url }}" alt="Imagen de perfil">
    {% else %}
    <i class="fas fa-user fa-fw fa-3x" style="color: white;"></i>
    {% endif %}
  </div>

  <div class="user-info">
    <h1 style="font-weight: 700;">{{ usuario.username }}</h1>
    <br>
    <p><span style="font-weight: 600;">Correo electrónico:</span>&nbsp;&nbsp;<span style="color: #777;">{{ usuario.email }}</span></p>
  </div>

  {% if roles %}
  <div class="roles">
    <p>
      <span style="font-weight: 600;">Roles:</span>&nbsp;
      <span style="color: #777;">
        {% for rol in roles %}
        {{ rol.nombre }}
        {% if not forloop.last %}&nbsp;{% endif %} <!-- Coma entre roles excepto el último -->
        {% endfor %}
    </span>
    </p>
  </div>
  {% else %}
  <p>{{ mensaje_roles }}</p>
  {% endif %}

  <div>
    <br>
    <nav class="custom-nav">
      <label for="imagen-input" class="custom-nav-item" style="cursor: pointer;">
        Cambiar Foto de Perfil
    </label>
    <input type="file" id="imagen-input" name="imagen" style="display: none;" accept="image/*">
    
    <script>
    document.getElementById('imagen-input').addEventListener('change', function() {
        var fileInput = this;
        if (fileInput.files.length > 0) {
            var formData = new FormData();
            formData.append('imagen', fileInput.files[0]);
            fetch("{% url 'login:cargar_imagen' %}", {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                }
            })
            .then(response => {
                if (response.status === 200) {
                    // La imagen se cargó exitosamente.
                    // Puedes redirigir o realizar alguna otra acción si es necesario.
                    window.location.href = "{% url 'login:perfil' %}";
                } else {
                    // Manejar errores si es necesario.
                }
            });
        }
    });
    </script>
    
      <a class="custom-nav-item" href="{% url 'login:perfil_actualizar' %}">Actualizar Perfil</a>
    </nav>
  </div>
  
  
  <hr style="width: 56%;margin: 0 auto; margin-top: 80px;">
</div>

<div class="lista">
  {% if publicaciones %}
    {% include 'cms/publicaciones.html' %}
  {% else %}
    <h5 class="sin_publicaciones"> No has publicado nada aún </h5>
  {% endif %}
  
</div>
{% endblock %}

templates/login/registro.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
  <!-- Enlaces para los íconos de favicon -->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon_io/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon_io/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon_io/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'favicon_io/site.webmanifest' %}">

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Registrarse</title>
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">
  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
  <!-- Custom styles for full-height container -->
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: black;
      margin: 0;
      padding: 0;
    }

    .row.justify-content-center {
      height: 100vh;
      /* Establece la altura al 100% del viewport (pantalla) */
    }

    .col-xl-12 {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100%;
      /* Establece la altura al 100% del viewport (pantalla) */
    }

    /* Cambios para el fondo y color del texto en la parte del login */
    .col-lg-3 {
      background-color: #000;
      color: #000;
      /* Color del texto en negro */
    }

    /* Resto de tus estilos CSS existentes */
  </style>
</head>

<body>
  <div class="row justify-content-center">
    <div class="col-lg-9 d-none d-lg-block bg-login-video">
      <video autoplay loop muted playsinline>
        <source src="{% static 'videos/background-videos.mp4' %}" type="video/mp4">
        <!-- Agrega formatos de video adicionales aquí, como WebM y Ogg, si es necesario -->
      </video>
    </div>
    <div class="col-lg-3 offset-lg-9">
      <div class="p-5">
        <div class="text-center">
          <h1 class="h5 text-gray-100 mb-4">CMS</h1>
        </div>
        <form method="post" action="{% url 'login:registro' %}" class="user">
          {% csrf_token %}

          <div class="form-group">
            <input type="text" class="form-control" name="username" placeholder="Usuario">
            {% if formulario.username.errors %}
            <ul class="errorlist">
              {% for error in formulario.username.errors %}
              <li>{{ error }}</li>
              {% endfor %}
            </ul>
            {% endif %}
          </div>

          <div class="form-group">
            <input type="email" name="email" class="form-control" placeholder="Correo electrónico">
            {% if formulario.email.errors %}
            <ul class="errorlist">
              {% for error in formulario.email.errors %}
              <li>{{ error }}</li>
              {% endfor %}
            </ul>
            {% endif %}
          </div>

          <div class="form-group">
            <input type="password" name="password1" class="form-control" placeholder="Contraseña">
            {% if formulario.password1.errors %}
            <ul class="errorlist">
              {% for error in formulario.password1.errors %}
              <li>{{ error }}</li>
              {% endfor %}
            </ul>
            {% endif %}
          </div>

          <div class="form-group">
            <input type="password" name="password2" class="form-control" placeholder="Confirmar contraseña">
            {% if formulario.password2.errors %}
            <ul class="errorlist">
              {% for error in formulario.password2.errors %}
              <li>{{ error }}</li>
              {% endfor %}
            </ul>
            {% endif %}
          </div>

          <button type="submit" class="btn btn-primary btn-block">Registrarse</button>
        </form>

        <hr>
        {% include 'mensajes.html' %}
        <div class="text-center">
          <p class="text-gray-100 mb-4">¿Ya tienes una cuenta? <a href="{% url 'login:inicio_sesion' %}">Inicia sesión
              aquí</a></p>
        </div>

      </div>
    </div>
  </div>
</body>


</html>