cms/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.principal, name='principal'),
    path('froala_editor/', include('froala_editor.urls')),
    path('login/', include('login.urls', namespace='login')),
    path('administracion/', include('administracion.urls', namespace='administracion')),
    path('publicaciones/', include('publicaciones.urls', namespace='publicaciones')),
    path('kanban/', include('kanban.urls', namespace='kanban')),
    path('comentarios/', include('comentarios.urls', namespace='comentarios')),
    path('categoria/<int:categoria_id>/', views.publicaciones_categoria, name='publicaciones_categoria'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kanban/urls.py
from django.urls import path
from . import views

app_name = 'kanvan' 

urlpatterns = [
    path('', views.kanban, name='kanban'),
    path('actualizar/', views.actualizar, name='actualizar'),
    path('motivo/', views.motivo, name='motivo'),
    path('historial/<uuid:publicacion_id>/', views.historial, name='historial'),
]

publicaciones/urls.py
from django.urls import path
from . import views

app_name = 'publicaciones'

urlpatterns = [
    path('crear/', views.crear_publicacion, name='crear_publicacion'),
    path('generar_qr/<uuid:publicacion_id>/', views.generar_qr, name='generar_qr'),
    path('editar/<uuid:publicacion_id>/autor/', views.editar_publicacion_autor, name='editar_publicacion_autor'),
    path('editar/<uuid:publicacion_id>/editor/', views.editar_publicacion_editor, name='editar_publicacion_editor'),
    path('ver/<uuid:publicacion_id>/', views.mostar_para_publicador, name='mostar_para_publicador'),
    path('mostrar/<uuid:publicacion_id>/', views.mostrar_publicacion, name='mostrar_publicacion'),
    path('compartidas/<uuid:publicacion_id>/', views.compartidas, name='compartidas'),
    path('like/<uuid:publicacion_id>/', views.like, name='like'),
    path('dislike/<uuid:publicacion_id>/', views.dislike, name='dislike'),
    path('track_view/<uuid:publicacion_id>/', views.track_view, name='track_view'),
    path('estado/<uuid:publicacion_id>/', views.estado, name='estado'),
    path('estatus/<uuid:publicacion_id>/', views.estatus, name='estatus'),
    path('calificar/<uuid:publicacion_id>/', views.calificar, name='calificar'),
]

kanban/models.py
from django.db import models
from login.models import Usuario
import uuid
from roles.models import Rol

class Registro(models.Model):
    """
    Clase que representa un registro de cambios en el sistema Kanban.

    Atributos:
    -----------
    publicacion_id : UUIDField
        ID único de la publicación.
    
    publicacion_titulo : CharField
        Título de la publicación.
    
    anterior : CharField, opcional
        Estado anterior de la publicación.
    
    nuevo : CharField, opcional
        Nuevo estado de la publicación.
    
    responsable : ForeignKey a Usuario, opcional
        Usuario responsable del cambio.
    
    roles : ManyToManyField a Rol, opcional
        Roles relacionados con el cambio.
    
    fecha_cambio : DateTimeField
        Fecha y hora del cambio.
    """
    publicacion_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=False)
    publicacion_titulo = models.CharField(max_length=255)
    anterior = models.CharField(max_length=20 , blank=True, null=True)
    nuevo = models.CharField(max_length=20 , blank=True, null=True)
    responsable = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True)
    roles = models.ManyToManyField(Rol, related_name='roles_responsable')
    fecha_cambio = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Método que devuelve una representación de cadena del registro.

        Returns:
        --------
        str
            Representación de cadena del registro.
        """       
        return f'Registro de {self.publicacion_titulo} por {self.responsable}'

kanban/views.py
from django.shortcuts import render
from publicaciones.models import Publicacion_solo_text
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404
from publicaciones.models import Publicacion_solo_text
from django.db.models import Q
from uuid import UUID
from django.http import Http404
from publicaciones.utils import tiene_rol
from roles.decorators import permiso_requerido
from django.contrib.auth.decorators import login_required
from .models import Registro
from administracion.models import Categoria
from publicaciones.utils import notificar
from login.models import Usuario
from datetime import datetime

@permiso_requerido
@login_required
def kanban(request):
    """
    Vista para el panel de kanban.

    Esta función obtiene y clasifica las publicaciones basadas en sus estados ('borrador', 'rechazado', 'revision', 'publicar', 'publicado'). 
    Solo se consideran las publicaciones que están activas y pertenecen a categorías moderadas.

    Parameters:
    -----------
    request : HttpRequest
        Objeto de solicitud HTTP.

    Returns:
    --------
    HttpResponse
        Respuesta HTTP con el tablero Kanban renderizado.

    Context Variables:
    ------------------
    - `publicaciones_borrador` : QuerySet
        Publicaciones con estado 'borrador' o 'rechazado' que no están destinadas al editor.
    - `publicaciones_revision` : QuerySet
        Publicaciones con estado 'revision' o 'rechazado' destinadas al editor.
    - `publicaciones_publicar` : QuerySet
        Publicaciones con estado 'publicar'.
    - `publicaciones_publicado` : QuerySet
        Publicaciones con estado 'publicado'.
    - `categorias` : QuerySet
        Categorías que están moderadas.

    Template:
    ---------
    - 'kanban/tablero.html'
    """
    publicaciones_borrador = Publicacion_solo_text.objects.filter(
    Q(estado='borrador', activo=True, categoria__moderada=True) |
    Q(estado='rechazado', para_editor=False, activo=True, categoria__moderada=True)
    )
    publicaciones_revision = Publicacion_solo_text.objects.filter(
    Q(estado='revision', activo=True, categoria__moderada=True) |
    Q(estado='rechazado', para_editor=True, activo=True, categoria__moderada=True)
    )
    publicaciones_publicar = Publicacion_solo_text.objects.filter(estado='publicar', activo=True, categoria__moderada=True)
    publicaciones_publicado = Publicacion_solo_text.objects.filter(estado='publicado', activo=True, categoria__moderada=True)

    categorias = Categoria.objects.filter(moderada=True)
    context = {
        'publicaciones_borrador': publicaciones_borrador,
        'publicaciones_revision': publicaciones_revision,
        'publicaciones_publicar': publicaciones_publicar,
        'publicaciones_publicado': publicaciones_publicado,
        'categorias': categorias
    }

    return render(request, 'kanban/tablero.html', context)

@permiso_requerido
@login_required
@csrf_exempt
def actualizar(request):
    """
    Actualiza el estado de una publicación basándose en el nuevo estado proporcionado en la solicitud POST.
    
    La función primero verifica si el método de solicitud es POST. A continuación, extrae el `id_publicacion` 
    y `nuevo_estado` de la solicitud. Luego, hay varias comprobaciones y condiciones para determinar la validez
    del cambio de estado y para realizar actualizaciones apropiadas. Si se cumple una condición inválida, 
    la función devuelve un objeto JsonResponse con un mensaje de error adecuado.
    
    Parameters:
    -----------
    request : HttpRequest
    La solicitud HTTP del cliente. Espera que el método de la solicitud sea POST y que contenga
    `id_publicacion` y `nuevo_estado` en el cuerpo de la solicitud.

    Returns:
    --------
    JsonResponse
    Una respuesta JSON que puede contener varios estados:
    - `vuelve`: Indica si la publicación debe regresar a su estado anterior.
    - `autor`: Indica si hay un error relacionado con el autor de la publicación.
    - `accion`: Indica si una cierta transición de estado no es permitida.
    - `reason_required`: Indica si se necesita una razón para una transición de estado.
    - `rol`: Indica si hay un error relacionado con el rol del usuario que realiza la solicitud.
    - `error`: Mensajes de error generales, como "No se encontró la publicación" o "ID no es válido".
    - `message`: Mensajes adicionales como "Método no permitido" para solicitudes que no son POST.

    Raises: 
    -------
    ValueError, Http404, Publicacion_solo_text.DoesNotExist
        Estas excepciones se manejan internamente y se devuelven como respuestas JSON con mensajes de error adecuados.
    """

    if request.method == 'POST':
        publicacion_id = request.POST.get('id_publicacion')        
        nuevo_estado = request.POST.get('nuevo_estado')

        estado_valor = {
            "rechazado": 0,
            "borrador": 1,
            "revision": 2,
            "publicar": 3,
            "publicado": 4
        }

        if nuevo_estado in estado_valor:
            try:
                publicacion_id = UUID(publicacion_id)
                publicacion = get_object_or_404(Publicacion_solo_text, id_publicacion=publicacion_id)
                anterior = publicacion.estado
                nuevo = nuevo_estado
                publicacion.estado = nuevo
                
                #asignacion temporal si estan rechazados
                if anterior == "rechazado" and publicacion.para_editor:
                    anterior="revision"
                elif anterior == "rechazado" and not publicacion.para_editor:
                    anterior = "borrador"
                
                #No se permiten recambios de estado en la misma columna
                if anterior == "borrador" and nuevo == "borrador":
                    return JsonResponse({'vuelve': True})
                if anterior == "revision" and nuevo == "revision":
                    return JsonResponse({'vuelve': True})
                if anterior == "publicar" and nuevo == "publicar":
                    return JsonResponse({'vuelve': True})
                if anterior == "publicado" and nuevo == "publicado":
                    return JsonResponse({'vuelve': True})
                                                
                #esta accion se restringe para el que no es el autor
                if nuevo == "revision" and anterior == "borrador" and not request.user == publicacion.autor:
                    return JsonResponse({'autor': True})
                
                #acciones no permitidas
                #publicado a revision
                #publicado a borrador
                #borrador a publicar
                #borrador a publicado
                #revision a publicado
                if anterior == "publicado" and nuevo == "revision":
                    return JsonResponse({'accion': False})
                if anterior == "publicado" and nuevo == "borrador":
                    return JsonResponse({'accion': False})
                if anterior == "borrador" and nuevo == "publicar":
                    return JsonResponse({'accion': False})
                if anterior == "borrador" and nuevo == "publicado":
                    return JsonResponse({'accion': False})
                if anterior == "revision" and nuevo == "publicado":
                    return JsonResponse({'accion': False})

                #Estas acciones corresponden a rechazos
                if nuevo == "borrador" and anterior == "revision" and tiene_rol(request.user, "editor"):
                    return JsonResponse({'reason_required': True})
                elif nuevo == "borrador" and anterior == "revision" and not tiene_rol(request.user, "editor"):
                    return JsonResponse({'rol': "editor"})
                if nuevo == "revision" and anterior == "publicar" and tiene_rol(request.user, "publicador"):
                    return JsonResponse({'reason_required': True})
                elif nuevo == "revision" and anterior == "publicar" and not tiene_rol(request.user, "publicador"):
                    return JsonResponse({'rol': "publicador"})
                if nuevo == "borrador" and anterior == "publicar" and tiene_rol(request.user, "publicador"):
                    return JsonResponse({'reason_required': True})
                elif nuevo == "borrador" and anterior == "publicar" and not tiene_rol(request.user, "publicador"):
                    return JsonResponse({'rol': "publicador"})
                
                #acciones que corresponden a ciertos roles
                if nuevo == "publicar" and anterior == "revision" and not tiene_rol(request.user, "editor"):
                    return JsonResponse({'rol': "editor"})
                if nuevo == "publicado" and anterior == "publicar" and not tiene_rol(request.user, "publicador"):
                    return JsonResponse({'rol': "publicador"})
                if nuevo == "publicar" and anterior == "publicado" and not tiene_rol(request.user, "publicador"):
                    return JsonResponse({'rol': "publicador"})
                
                print(publicacion.estado)
                print(publicacion.para_editor)
                print(publicacion.semaforo)
                
                publicacion.semaforo = "rojo"                
                if publicacion.estado == "publicado":
                    publicacion.semaforo = "verde"
                    publicacion.fecha_publicacion = datetime.now().date()

                publicacion.save()
                if not publicacion.estado == "borrador":
                    notificar(publicacion,3)

                registrar(request, publicacion, anterior)
                
                return JsonResponse({'vuelve': True})
            except (ValueError, Http404, Publicacion_solo_text.DoesNotExist) as e:

templates/kanban/historial.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <br>
    <h1>Historial</h1>
    <br>
    {% if registros %}    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Título de la Publicación</th>
                <th>Anterior Estado</th>
                <th>Nuevo Estado</th>
                <th>Responsable</th>
                <th>Roles</th>
                <th>Fecha de Cambio</th>
            </tr>
        </thead>
        <tbody>
            {% for registro in registros %}
            <tr>
                <td>{{ registro.publicacion_titulo }}</td>
                <td>{{ registro.anterior }}</td>
                <td>{{ registro.nuevo }}</td>
                <td>{{ registro.responsable }}</td>
                <td>
                    {% for rol in registro.roles.all %}
                        {{ rol }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
                <td>{{ registro.fecha_cambio }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p style="color: gray; margin-left: 5px;">No tienes registros</p>
    {% endif %}
    <a href="{% url 'kanban:kanban' %}" style="margin-left: 5px;">Volver al Tablero</a>
</div>
{% endblock %}

templates/kanban/motivo.html
<div class="modal fade" id="motivoModal" tabindex="-1" role="dialog" aria-labelledby="motivoModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="motivoModalLabel">Motivo del Rechazo</h5>
            </div>
            <div class="modal-body">
                <input type="text" id="motivoInput" class="form-control" placeholder="Ingrese el motivo del rechazo">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="guardarMotivoBtn">Guardar Motivo</button>
                <button type="button" class="btn btn-secondary" id="cerrarMotivoBtn">Cerrar</button>
            </div>
        </div>
    </div>
</div>

templates/kanban/tablero.html
{% extends "base.html" %}
{% load static %}
{% load custom_tags %}
{% block title %}kanban{% endblock %}
{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.14.0/Sortable.min.js"></script>
<link href="{% static 'css/tablero.css' %}" rel="stylesheet" />
<script src="{% static 'js/tablero.js' %}"></script>
<style>
    .contenedor {
        /*max-width: 1200px;*/
        margin: 10px auto;
        padding: 10px;
    }
</style>
<div class="contenedor">
    <h3 class="kanban-columns">Tablero kanban</h3>
    <div class="kanban-columns">
        <!-- Columna "Borrador" -->
        <div class="kanban-column" id="borrador">
            <span class="kanban-column-title">Borrador</span>
            {% for publicacion in publicaciones_borrador %}
            <li class="sortable-item sortable-list" id="{{ publicacion.id_publicacion }}" data-draggable="true" color="{{publicacion.semaforo}}">
                {% if user == publicacion.autor %}
                <a href="{% url 'publicaciones:editar_publicacion_autor' publicacion.id_publicacion %}">
                {% else %}
                <a href="#">
                {% endif %}
                    {% include 'kanban/tarjeta.html' with publicacion=publicacion %}
                </a>
            </li>
            {% endfor %}
        </div>
        <!-- Columna "Revisión" -->
        <div class="kanban-column" id="revision">
            <span class="kanban-column-title">Revisión</span>
            {% for publicacion in publicaciones_revision %}
            <li class="sortable-item sortable-list" id="{{ publicacion.id_publicacion }}" data-draggable="true" color="{{publicacion.semaforo}}">
                {% if user|has_role:"editor" %}
                <a href="{% url 'publicaciones:editar_publicacion_editor' publicacion.id_publicacion %}">
                {% else %}
                <a href="#">
                {% endif %}
                    {% include 'kanban/tarjeta.html' with publicacion=publicacion %}
                </a>
            </li>
            {% endfor %}
        </div>
        <!-- Columna "Publicar" -->
        <div class="kanban-column" id="publicar">
            <span class="kanban-column-title">Publicar</span>
            {% for publicacion in publicaciones_publicar %}
            <li class="sortable-item sortable-list" id="{{ publicacion.id_publicacion }}" data-draggable="true" color="{{publicacion.semaforo}}">
                {% if user|has_role:"publicador" %}
                <a href="{% url 'publicaciones:mostar_para_publicador' publicacion.id_publicacion %}">
                {% else %}
                <a href="#">
                {% endif %}                
                    {% include 'kanban/tarjeta.html' with publicacion=publicacion %}
                </a>
            </li>
            {% endfor %}
        </div>
        <!-- Columna "Publicado" -->
        <div class="kanban-column" id="publicado">
            <span class="kanban-column-title">Publicado</span>
            {% for publicacion in publicaciones_publicado %}
            <li class="sortable-item sortable-list" id="{{ publicacion.id_publicacion }}" data-draggable="true" color="{{publicacion.semaforo}}">
                <a href="#">
                    {% include 'kanban/tarjeta.html' with publicacion=publicacion %}
                </a>
            </li>
            {% endfor %}
        </div>
    </div>
</div>
{% include 'kanban/motivo.html' %}
{% endblock %}

templates/kanban/tarjeta.html
<style>
    .tarjeta-fecha {
        font-size: 12px;
        color: #888;
        /* Gris */
    }

    .tarjeta-info {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .tarjeta-categoria {
        padding: 0px 5px 3px;
        /* Ajustar el espacio vertical y horizontal */
        color: #fff;
        /* Blanco */
        border-radius: 5px;
    }

    .categoria-text {
        font-size: 13px;
    }

    .tarjeta-autor img {
        vertical-align: middle;
    }

    .tarjeta-autor-nombre {
        font-weight: bold;
        color: #000;
        /* Negro */
        margin-left: 5px;
    }

    .lamp {
        width: 11px;
        height: 11px;
        border-radius: 50%;
        background-color: white;
        transition: box-shadow 0.3s ease-in-out;
        position: relative; /* Agregamos posición relativa */
        top: 1px;
        margin-left: 3px;   
        display: inline-block;
    }

    .red {
        background-color: rgb(255, 0, 0); /* Rojo brillante */
        box-shadow: 0 0 4px rgba(255, 0, 0, 0.8); /* Efecto de sombra */
    }

    .yellow {
        background-color: yellow;
        box-shadow: 0 0 4px rgba(255, 255, 0, 0.8);
    }

    .green {
        background-color: #00FF00; /* Un verde más brillante */
        box-shadow: 0 0 4px rgba(0, 255, 0, 0.8); /* Efecto de sombra */
    }

    .title-lamp {
        flex-direction: column;
    }

    .title {
        font-weight: bold;
        color: #0074b2;
        display: inline-block;
    }

    /* Resto de estilos como se definió previamente para .red, .yellow, .green, y .lamp */
</style>
<div class="tarjeta-contenido">
    <div class="title-lamp">
        <span class="title">{{ publicacion.titulo }} <span class="lamp {% if publicacion.semaforo == 'rojo' %}red{% elif publicacion.semaforo == 'amarillo' %}yellow{% elif publicacion.semaforo == 'verde' %}green{% endif %}"></span></span>
    </div>
    <span class="tarjeta-fecha">{{ publicacion.fecha_creacion|date:"d, M Y" }} <span style="margin-left: 3px;"><a href="{% url 'kanban:historial' publicacion.id_publicacion %}"><i class="fas fa-history"></i></a></span></span>
    <br> <!-- Línea vacía -->
    <br> <!-- Línea vacía -->
    <div class="tarjeta-info">
        <div class="tarjeta-categoria" style="background-color: {{publicacion.categoria.color}}">
            <span class="categoria-text">{{ publicacion.categoria }}</span>
        </div>
        <div class="tarjeta-autor">
            {% if publicacion.autor.imagen %}
            <img src="{{ publicacion.autor.imagen.url }}" class="rounded-circle" width="30" height="30"
                style="object-fit: cover;">
            {% else %}
            <i class="fas fa-user"></i>
            {% endif %}
            <span class="tarjeta-autor-nombre">{{ publicacion.autor.username }}</span>
        </div>
    </div>
</div>