administracion/urls.py
from django.urls import path
from . import views

app_name = 'administracion'

urlpatterns = [
    path('', views.panel, name='panel'),
    path('categorias/', views.gestion_categorias, name='gestion_categorias'),
    path('categorias/crear/', views.crear_categoria, name='crear_categoria'),
    path('categorias/editar/<int:categoria_id>/', views.editar_categoria, name='editar_categoria'),
    path('categorias/eliminar/<int:categoria_id>/', views.eliminar_categoria, name='eliminar_categoria'),
    path('usuarios/', views.gestion_usuarios, name='gestion_usuarios'), 
    path('usuarios/eliminar/<int:usuario_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('usuarios/crear_rol/', views.crear_rol, name='crear_rol'),
    path('usuarios/asignar_roles/<int:usuario_id>/', views.asignar_roles_usuario, name='asignar_roles_usuario'),
    path('usuarios/eliminar_roles/<int:usuario_id>/', views.eliminar_roles_usuario, name='eliminar_roles_usuario'),
    path('usuarios/agregar_permisos/<int:usuario_id>/', views.agregar_permisos_roles_usuario, name='agregar_permisos_roles_usuario'),
    path('usuarios/eliminar_permisos/<int:usuario_id>/', views.eliminar_permisos_roles_usuario, name='eliminar_permisos_roles_usuario'),
    path('favorito/<int:categoria_id>/', views.favorito, name='favorito'),
]

cms/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.principal, name='principal'),
    path('froala_editor/', include('froala_editor.urls')),
    path('login/', include('login.urls', namespace='login')),
    path('administracion/', include('administracion.urls', namespace='administracion')),
    path('publicaciones/', include('publicaciones.urls', namespace='publicaciones')),
    path('kanban/', include('kanban.urls', namespace='kanban')),
    path('comentarios/', include('comentarios.urls', namespace='comentarios')),
    path('categoria/<int:categoria_id>/', views.publicaciones_categoria, name='publicaciones_categoria'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kanban/urls.py
from django.urls import path
from . import views

app_name = 'kanvan' 

urlpatterns = [
    path('', views.kanban, name='kanban'),
    path('actualizar/', views.actualizar, name='actualizar'),
    path('motivo/', views.motivo, name='motivo'),
    path('historial/<uuid:publicacion_id>/', views.historial, name='historial'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'  

urlpatterns = [
    path('', views.inicio_sesion, name='inicio_sesion'),
    path('registro/', views.registro, name='registro'),
    path('cerrar-sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path('perfil/', views.perfil_usuario, name='perfil'),
    path('perfil/actualizar/', views.perfil_actualizar, name='perfil_actualizar'),
    path('perfil/cargar_imagen/', views.cargar_imagen, name='cargar_imagen'),
]

publicaciones/urls.py
from django.urls import path
from . import views

app_name = 'publicaciones'

urlpatterns = [
    path('crear/', views.crear_publicacion, name='crear_publicacion'),
    path('generar_qr/<uuid:publicacion_id>/', views.generar_qr, name='generar_qr'),
    path('editar/<uuid:publicacion_id>/autor/', views.editar_publicacion_autor, name='editar_publicacion_autor'),
    path('editar/<uuid:publicacion_id>/editor/', views.editar_publicacion_editor, name='editar_publicacion_editor'),
    path('ver/<uuid:publicacion_id>/', views.mostar_para_publicador, name='mostar_para_publicador'),
    path('mostrar/<uuid:publicacion_id>/', views.mostrar_publicacion, name='mostrar_publicacion'),
    path('compartidas/<uuid:publicacion_id>/', views.compartidas, name='compartidas'),
    path('like/<uuid:publicacion_id>/', views.like, name='like'),
    path('dislike/<uuid:publicacion_id>/', views.dislike, name='dislike'),
    path('track_view/<uuid:publicacion_id>/', views.track_view, name='track_view'),
    path('estado/<uuid:publicacion_id>/', views.estado, name='estado'),
    path('estatus/<uuid:publicacion_id>/', views.estatus, name='estatus'),
    path('calificar/<uuid:publicacion_id>/', views.calificar, name='calificar'),
]

templates/base.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="es">

{% comment %} <script>
    // Se define una variable global que puede ser usada por otros scripts.
    window.CMSData = {
        'publicacionId': null
    };
</script> {% endcomment %}

<head>

     <!-- Google tag (gtag.js) -->
     <script async src="https://www.googletagmanager.com/gtag/js?id=G-8PCDK3WX2T"></script>
     <script>
         window.dataLayer = window.dataLayer || [];
         var publicacionId = '{{ publicacion.id_publicacion }}';
         console.log(publicacionId)
         function gtag(){dataLayer.push(arguments);}
         gtag('js', new Date());

         gtag('config', 'G-8PCDK3WX2T', {
             'page_path': '/publicaciones/mostrar/' + publicacionId
         });
     </script>

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-NKFGJZ53');</script>
    <!-- End Google Tag Manager -->

    <title>{% block title %} {% endblock %}</title>
    <!-- Enlaces para los íconos de favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon_io/site.webmanifest' %}">

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--Para los iconos de los accesos en el sidebar-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'css/buscador.css' %}" rel="stylesheet" />

</head>

<!-- Si quitas el class que tiene body, al hacer scroll no se mantendra la parte superior-->
<body class="sb-nav-fixed">

    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NKFGJZ53"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <!-- Este es todo el Navbar-->
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Sidebar Toggle Button -->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#/"><i class="fas fa-bars"></i></button>

        <!-- Logo del Navbar -->
        <a class="navbar-brand ps-3" href="/">CMS</a>

        <!-- Contenedor para centrar el buscador y el botón "+" -->
        <div class="mx-auto">
            <form id="search-form" action="{% url 'principal' %}" method="GET">
                {% csrf_token %}
                <div id="search-container">
                    <input type="text" id="q" name="q" placeholder="Buscar">
                    <a id="gris" href="javascript:void(0);">
                        <i class="fas fa-search"></i>
                    </a>
                    {% if principal %}
                    <div id="filter-icon">
                        <a class="nav-link" id="btnMostrarBusquedaAvanzada" href="#!" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-cog"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <h6 class="dropdown-header">Búsqueda Avanzada</h6>
                            <div class="dropdown-item">{{ avanzada_form.as_p }}</div>
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </form>
        </div>

        <!-- Navbar Dropdown (Usuario) -->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#!" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {% if user.imagen %}
                    <img src="{{ user.imagen.url }}" alt="{{ user.username }}" class="rounded-circle" width="40" height="40" style="object-fit: cover;">
                    {% else %}
                    <i class="fas fa-user fa-fw"></i>
                    {% endif %}
                    <span style="margin-left: 6px; font-weight: 600;">{{user.username}}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'login:perfil' %}">Perfil</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="{% url 'login:cerrar_sesion' %}">Cerrar sesión</a></li>
                    {% else %}
                    <li><a class="dropdown-item" href="{% url 'login:inicio_sesion' %}">Acceder</a></li>
                    {% endif %}
                </ul>
            </li>
        </ul>
    </nav>

    <!-- Este es todo el Sidebar-->
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">

                            <div class="sb-sidenav-menu-heading">Principal</div>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse"
                                    data-bs-target="#collapseLayoutsPublicaciones" aria-expanded="false" aria-controls="collapseLayouts">
                                    <div class="sb-nav-link-icon"><i class="fas fa-file-alt"></i></div>
                                    Publicaciones
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="collapseLayoutsPublicaciones" aria-labelledby="headingOne"
                                    data-bs-parent="#sidenavAccordion">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="/">Inicio</a>

                                        {% if user.roles %}
                                            {% for rol in user.roles.all %}
                                                {% if rol.nombre == 'autor' %}
                                                    <a class="nav-link" href="{% url 'publicaciones:crear_publicacion' %}">Crear Publicación</a>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    </nav>
                                </div>
                        {% if user.is_authenticated %}
                            {% if user|has_role:"autor,editor,publicador" %}
                                <div class="sb-sidenav-menu-heading">Kanban</div>
                                <a class="nav-link" href="{% url 'kanban:kanban' %}">
                                    <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                    Tablero
                                </a>
                            {% endif %}
                        {% endif %}


                        {% for rol in user.roles.all %}
                            {% if rol.nombre == 'administrador' %}
                                <div class="sb-sidenav-menu-heading">Panel</div>
                                <a class="nav-link" href="{% url 'administracion:panel' %}">
                                    <div class="sb-nav-link-icon"><i class="fas fa-desktop-alt"></i></div>
                                    Administracion
                                </a>
                            {% endif %}
                        {% endfor %}

                    </div>
                </div>
            </nav>
        </div>

        <!-- Este es todo el contenido, parece que va dentro del Sidebar-->
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    {% block content %}{% endblock %}
                </div>
            </main>

            <!-- Este es todo el copyright del final-->
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/buscador.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% include 'mensajes.html' %}

    {% block javascript %}
        <script>
            // Asegúrate de que estas funciones se definen después de que gtag.js esté cargado
            function sendLikeEvent(publicacionId) {
                gtag('event', 'like', {
                    'event_category': 'Interacción',
                    'event_label': 'Publicación ' + publicacionId,
                    'value': 1
                });
                console.log("Evento de like enviado para la publicación:", publicacionId);
            }

            {% comment %} function sendDislikeEvent(publicacionId) {
                gtag('event', 'dislike', {
                    'event_category': 'Interacción',
                    'event_label': 'Publicación ' + publicacionId,
                    'value': 1
                });
                console.log("Evento de dislike enviado para la publicación:", publicacionId);
            } {% endcomment %}

            function sendCommentEvent(publicacionId) {
                gtag('event', 'comment', {
                    'event_category': 'Interacción',
                    'event_label': 'Publicación ' + publicacionId,
                    'value': 1
                });
                console.log("Evento de comentario enviado para la publicación:", publicacionId);
            }

            {% comment %} function sendViewEvent(publicacionId) {
                gtag('event', 'view', {
                    'event_category': 'Interacción',
                    'event_label': 'Publicación ' + publicacionId,
                    'value': 1
                });
                console.log("Evento de vista enviado para la publicación:", publicacionId);
            } {% endcomment %}

            function sendShareEvent(publicacionId) {
                gtag('event', 'compartir', {
                    'event_category': 'Interacción',
                    'event_label': 'Publicación ' + publicacionId,
                    'value': 1
                });
                console.log("Evento de compartir enviado para la publicación:", publicacionId);
            }
        </script>

    {% endblock %}

</body>

</html>

templates/mensajes.html
<!-- JavaScript y CSS para SweetAlert2 -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<!-- JavaScript para mostrar el mensaje de éxito con SweetAlert2 -->
    {% if messages %}
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                Swal.fire({
                    //title: 'Mensaje de éxito',
                    //backdrop: 'static',
                    allowOutsideClick: false, // Evita que se cierre haciendo clic fuera
                    html: `{% for message in messages %}<p>{{ message }}</p>{% endfor %}`,
                    icon: `{% for message in messages %}{{ message.tags }}{% endfor %}`,
                    showConfirmButton: true, // Mostrar el botón de confirmación
                    customClass: {
                        confirmButton: 'custom-confirm-button btn btn-primary', // Clase CSS personalizada para el botón de confirmación
                    },
                    confirmButtonText: 'Aceptar',
                    buttonsStyling: false,
                    
                }).then((result) => {
                    //if (result.isConfirmed) {
                    //    window.location.href = "{{ redirect_url }}"
                    //}
                    
                    //if (redirectUrl !== null && result.isConfirmed) {
                    //   window.location.href = redirectUrl;
                    //}

                    //if (redirectUrl && redirectUrl !== "None" && result.isConfirmed) {
                    //    window.location.href = redirectUrl;
                    //}
                    var redirectUrl = "{{ redirect_url }}";
                    if (result.isConfirmed && redirectUrl && redirectUrl !== "None") {
                        window.location.href = redirectUrl;
                    }
                });
            });
        </script>
        <style>
            .custom-confirm-button {
                background-color: #007BFF; /* Color de fondo personalizado */
                border-color: #007BFF; /* Color del borde personalizado (opcional) */
                color: white !important; /* Color del texto personalizado */
            }
        </style>
{% endif %}