administracion/urls.py
from django.urls import path
from . import views

app_name = 'administracion'

urlpatterns = [
    path('', views.panel, name='panel'),
    path('categorias/', views.gestion_categorias, name='gestion_categorias'),
    path('categorias/crear/', views.crear_categoria, name='crear_categoria'),
    path('categorias/editar/<int:categoria_id>/', views.editar_categoria, name='editar_categoria'),
    path('categorias/eliminar/<int:categoria_id>/', views.eliminar_categoria, name='eliminar_categoria'),
    path('usuarios/', views.gestion_usuarios, name='gestion_usuarios'), 
    path('usuarios/eliminar/<int:usuario_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('usuarios/crear_rol/', views.crear_rol, name='crear_rol'),
    path('usuarios/asignar_roles/<int:usuario_id>/', views.asignar_roles_usuario, name='asignar_roles_usuario'),
    path('usuarios/eliminar_roles/<int:usuario_id>/', views.eliminar_roles_usuario, name='eliminar_roles_usuario'),
    path('usuarios/agregar_permisos/<int:usuario_id>/', views.agregar_permisos_roles_usuario, name='agregar_permisos_roles_usuario'),
    path('usuarios/eliminar_permisos/<int:usuario_id>/', views.eliminar_permisos_roles_usuario, name='eliminar_permisos_roles_usuario'),
    path('favorito/<int:categoria_id>/', views.favorito, name='favorito'),
]

cms/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.principal, name='principal'),
    path('froala_editor/', include('froala_editor.urls')),
    path('login/', include('login.urls', namespace='login')),
    path('administracion/', include('administracion.urls', namespace='administracion')),
    path('publicaciones/', include('publicaciones.urls', namespace='publicaciones')),
    path('kanban/', include('kanban.urls', namespace='kanban')),
    path('comentarios/', include('comentarios.urls', namespace='comentarios')),
    path('categoria/<int:categoria_id>/', views.publicaciones_categoria, name='publicaciones_categoria'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administracion/models.py
from django.db import models
import secrets
from login.models import Usuario

def get_random_color():
    while True:
        color = f'#{secrets.token_hex(3)}'
        if color != '#FFFFFF' and not Categoria.objects.filter(color=color).exists():
            return color

class Categoria(models.Model):
    """
    Modelo que representa una categoría para las publicaciones.

    Atributos:
        nombre (str): El nombre único de la categoría.
        moderada (bool): Indica si la categoría está moderada o no.
        descripcion (str): Una descripción de la categoría.
        color (str): Color único asignado a la categoría.

    Métodos:
        __str__(): Devuelve una representación de cadena del objeto, que es el nombre de la categoría.

    """
    nombre = models.CharField(max_length=30, unique=True)
    moderada = models.BooleanField(default=False)
    descripcion = models.TextField(blank=True, null=True)
    suscriptores = models.BooleanField(default=False)
    favorito_usuario = models.ManyToManyField(Usuario, blank=True, related_name='categorias_favoritos')
    color = models.CharField(max_length=7)
    
    def save(self, *args, **kwargs):
        """
        Método personalizado para guardar la categoría y asignar un color único si no se proporciona.

        Parameters:
        -----------
        `*args`, `**kwargs`:
            Argumentos adicionales para el método de guardar.
        """
        if not self.color:
            self.color = get_random_color()
        super().save(*args, **kwargs)

    def __str__(self):
        """
        Devuelve una representación en cadena del objeto, que es el nombre de la categoría.

        Returns:
        --------
        str
            Representación en cadena del nombre de la categoría.
        """
        return self.nombre

administracion/forms.py
from django import forms
from .models import Categoria
from login.models import Usuario
from roles.models import Rol
from django.contrib.auth.models import Permission

class CategoriaForm(forms.ModelForm):
    """
    Formulario para crear y editar una categoría.

    Este formulario se utiliza para ingresar información sobre una categoría,
    incluyendo su nombre, descripción y estado de moderación.
    """

    class Meta:
        model = Categoria
        fields = ['nombre', 'descripcion', 'moderada','suscriptores']

    def __init__(self, *args, **kwargs):
        super(CategoriaForm, self).__init__(*args, **kwargs)

class AsignarPermisosForm(forms.Form):
    """
    Formulario para asignar permisos a roles de usuario.

    Este formulario se utiliza para asignar permisos específicos a roles de usuario
    en el sistema.
    """
    permisos = forms.MultipleChoiceField(
        choices=(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    def __init__(self, *args, roles_asignados=None, **kwargs):
        super(AsignarPermisosForm, self).__init__(*args, **kwargs)

        if roles_asignados:
            # Limitar las opciones de roles a los roles asignados al usuario
            self.fields['rol'] = forms.ModelChoiceField(
                queryset=roles_asignados,
                label='Rol',
                required=True
            )

            # Obtener todos los nombres de permisos en la clase Rol
            nombres_permisos_roles = []
            for rol_permisos in Rol.PERMISOS.values():
                nombres_permisos_roles.extend(rol_permisos)

            # Obtener los permisos asignados a los roles del usuario
            permisos_asignados = Permission.objects.filter(rol__in=roles_asignados).values_list('codename', flat=True)

            # Obtener los nombres de permisos disponibles excluyendo los ya asignados
            permisos_disponibles = set(nombres_permisos_roles) - set(permisos_asignados)

            # Configurar las opciones del campo permisos
            self.fields['permisos'].choices = [(nombre, nombre) for nombre in permisos_disponibles]
        else:
            self.fields['rol'] = forms.ModelChoiceField(
                queryset=Rol.objects.none(),  # Si no hay roles asignados, no mostrar ningún rol
                label='Rol',
                required=True
            )
            
class EliminarPermisosForm(forms.Form):
    """
    Formulario para eliminar permisos de roles de usuario.

    Este formulario se utiliza para seleccionar y eliminar permisos de roles de usuario
    en el sistema.
    """
    permisos = forms.ModelMultipleChoiceField(
        queryset=Permission.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

administracion/views.py
from django.shortcuts import render, get_object_or_404
from .models import Categoria
from .forms import CategoriaForm, AsignarPermisosForm, EliminarPermisosForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from roles.decorators import rol_requerido, permiso_requerido
from roles.models import Rol
from login.models import Usuario
from django.urls import reverse
from roles.forms import AgregarRolForm
from django.http import JsonResponse

@rol_requerido('administrador')
@login_required
def panel(request):
    """
    Vista para el panel de administración.

    Parámetros:
        request (HttpRequest): La solicitud HTTP entrante.

    Retorna:
        HttpResponse: Redirecciona a la vista del panel de administración principal.
    """
    # Tu lógica para el panel principal va aquí
    return render(request, 'administracion/panel.html')

@rol_requerido('administrador')
@permiso_requerido
@login_required
def gestion_categorias(request):
    """
    Vista para listar categorías.

    Parámetros:
        request (HttpRequest): La solicitud HTTP entrante.

    Retorna:
        HttpResponse: Muestra la lista de categorías.
    """
    categorias = Categoria.objects.all()
    return render(request, 'administracion/gestion_categorias.html', {'categorias': categorias})

@rol_requerido('administrador')
@permiso_requerido
@login_required
def crear_categoria(request):
    """
    Vista para crear una nueva categoría.

    Parámetros:
        request (HttpRequest): La solicitud HTTP entrante.

    Retorna:
        HttpResponse: Redirecciona a la vista de lista de categorías si la categoría se crea con éxito,
        o muestra el formulario de creación de categoría con errores.
    """
    redirect_url = None
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'La categoría se ha creado correctamente.')
            redirect_url = reverse('administracion:gestion_categorias')
        else:
            messages.error(request, 'Hubo un problema al crear la categoría. Por favor, verifica los datos ingresados.')
            redirect_url = request.path
    else:
        form = CategoriaForm()

    return render(request, 'administracion/crear_categoria.html', {'form': form,'redirect_url': redirect_url})

@rol_requerido('administrador')
@permiso_requerido
@login_required
def editar_categoria(request, categoria_id):
    """
    Vista para editar una categoría existente.

    Parámetros:
        request (HttpRequest): La solicitud HTTP entrante.
        categoria_id (int): El ID de la categoría que se va a editar.

    Retorna:
        HttpResponse: Redirecciona a la vista de lista de categorías si la categoría se edita con éxito,
        o muestra el formulario de edición de categoría con errores.
    """
    redirect_url = None
    categoria = get_object_or_404(Categoria, pk=categoria_id)
    if request.method == 'POST':
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
            messages.success(request, 'La categoría se ha actualizado correctamente.')
            redirect_url = reverse('administracion:gestion_categorias')
        else:
            messages.error(request, 'Hubo un problema al actualizar la categoría. Por favor, verifica los datos ingresados.')
            redirect_url = request.path
    else:
        form = CategoriaForm(instance=categoria)
    return render(request, 'administracion/editar_categoria.html', {'form': form, 'categoria': categoria, 'redirect_url': redirect_url})

@rol_requerido('administrador')
@permiso_requerido
@login_required
def eliminar_categoria(request, categoria_id):
    """
    Vista para eliminar una categoría existente.

    Parámetros:
        request (HttpRequest): La solicitud HTTP entrante.
        categoria_id (int): El ID de la categoría que se va a eliminar.

    Retorna:
        HttpResponse: Redirecciona a la vista de lista de categorías si la categoría se elimina con éxito,
        o muestra la confirmación de eliminación de categoría con errores.
    """
    redirect_url = None
    categoria = get_object_or_404(Categoria, pk=categoria_id)
    if request.method == 'POST':
        categoria.delete()
        messages.success(request, 'La categoría se ha eliminado correctamente.')
        redirect_url = reverse('administracion:gestion_categorias')
    return render(request, 'administracion/eliminar_categoria.html', {'categoria': categoria, 'redirect_url': redirect_url})

@rol_requerido('administrador')
@permiso_requerido
@login_required
def gestion_usuarios(request):
    """
    Vista para gestionar usuarios.

    Parámetros:
        request (HttpRequest): La solicitud HTTP entrante.

    Retorna:
        HttpResponse: Muestra la lista de usuarios y opciones de eliminación.
    """
    usuarios = Usuario.objects.all()
    return render(request, 'administracion/gestion_usuarios.html', {'usuarios': usuarios})

@rol_requerido('administrador')
@permiso_requerido
@login_required
def eliminar_usuario(request, usuario_id):
    """
    Vista para eliminar un usuario existente.

    Esta vista permite a un administrador eliminar un usuario existente del sistema.
    
    Parámetros:
        request (HttpRequest): La solicitud HTTP entrante.
        usuario_id (int): El ID del usuario que se va a eliminar.

    Retorna:
        HttpResponse: Una respuesta HTTP que redirige al administrador a la lista de usuarios
                      después de eliminar el usuario especificado.

    """
    usuario = get_object_or_404(Usuario, id=usuario_id)
    redirect_url = None
    if request.method == 'POST':
        if usuario == request.user:    
            messages.error(request, 'No puedes eliminarte a ti mismo.')
        else:
            usuario.delete()
            messages.success(request, 'Usuario eliminado correctamente.')
        redirect_url = reverse('administracion:gestion_usuarios')

    return render(request, 'administracion/eliminar_usuario.html', {'usuario': usuario, 'redirect_url': redirect_url})

@rol_requerido('administrador')
@permiso_requerido
@login_required
def asignar_roles_usuario(request, usuario_id):
    """
    Vista para asignar roles a un usuario existente.

    Esta vista permite a un administrador asignar roles a un usuario existente en el sistema.

    Parámetros:
        request (HttpRequest): La solicitud HTTP entrante.
        usuario_id (int): El ID del usuario al que se le asignarán roles.

    Retorna:
        HttpResponse: Una respuesta HTTP que redirige al administrador a la gestión de usuarios
                      después de asignar los roles al usuario especificado.

    """    
    usuario = get_object_or_404(Usuario, id=usuario_id)
    redirect_url = None
    # Obtener los nombres de roles que el usuario aún no tiene asignados
    roles_asignados_nombres = usuario.roles.values_list('nombre', flat=True)
    roles_disponibles = [rol[0] for rol in Rol.ROLES if rol[0] not in roles_asignados_nombres]

    if request.method == 'POST':
        roles_seleccionados = request.POST.getlist('roles')
        for rol_nombre in roles_seleccionados:
            # Crear una nueva instancia del rol y asignarlo al usuario
            if rol_nombre not in roles_asignados_nombres:
                Rol.objects.create(nombre=rol_nombre)
                usuario.roles.create(nombre=rol_nombre)
        messages.success(request, 'Roles asignados correctamente.')
        redirect_url = reverse('administracion:gestion_usuarios')

    return render(request, 'administracion/asignar_roles_usuario.html', {'usuario': usuario, 'roles_disponibles': roles_disponibles, 'redirect_url': redirect_url})

@rol_requerido('administrador')
@permiso_requerido
@login_required
def eliminar_roles_usuario(request, usuario_id):
    """
    Vista para eliminar roles de un usuario existente.

    Esta vista permite a un administrador eliminar roles de un usuario existente en el sistema.

    Parámetros:
        request (HttpRequest): La solicitud HTTP entrante.
        usuario_id (int): El ID del usuario del que se eliminarán roles.

    Retorna:
        HttpResponse: Una respuesta HTTP que redirige al administrador a la gestión de usuarios
                      después de eliminar los roles del usuario especificado.

    """
    usuario = get_object_or_404(Usuario, id=usuario_id)
    redirect_url = None
    if request.method == 'POST':
        roles_seleccionados = request.POST.getlist('roles')
        for rol_id in roles_seleccionados:
            rol = Rol.objects.get(id=rol_id)
            usuario.roles.remove(rol)
        messages.success(request, 'Roles eliminados correctamente.')
        redirect_url = reverse('administracion:gestion_usuarios')

    roles_asignados = usuario.roles.all()
    return render(request, 'administracion/eliminar_roles_usuario.html', {'usuario': usuario, 'roles_asignados': roles_asignados, 'redirect_url': redirect_url})

@rol_requerido('administrador')
@permiso_requerido
@login_required
def agregar_permisos_roles_usuario(request, usuario_id):
    """
    Vista para agregar permisos a los roles de un usuario existente.

    Esta vista permite a un administrador agregar permisos a los roles de un usuario existente en el sistema.

    Parámetros:
        request (HttpRequest): La solicitud HTTP entrante.
        usuario_id (int): El ID del usuario al que se le asignarán permisos a sus roles.

    Retorna:
        HttpResponse: Una respuesta HTTP que redirige al administrador a la gestión de usuarios
                      después de agregar los permisos a los roles del usuario especificado.

    """    
    redirect_url = None
    usuario = Usuario.objects.get(id=usuario_id)
    roles_asignados = usuario.roles.all()

    if request.method == 'POST':

templates/administracion/agregar_permisos_roles_usuario.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Asignar Permisos a Roles del Usuario</h1>

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.rol.id_for_label }}">Rol:</label>
            {{ form.rol }}
        </div>
        <div class="form-group">
            <label>Permisos:</label>
            <ul class="list-group">
                {% for permiso in form.permisos %}
                <li class="list-group-item">
                    {{ permiso }}
                </li>
                {% endfor %}
            </ul>
        </div>

        <button type="submit" class="btn btn-primary">Agregar</button>
        <a href="{% url 'administracion:gestion_usuarios' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/administracion/asignar_roles_usuario.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Asignar Roles a {{ usuario.username }}</h1>

    <form method="post" action="{% url 'administracion:asignar_roles_usuario' usuario.id %}">
        {% csrf_token %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Rol</th>
                    <th>Seleccionar</th>
                </tr>
            </thead>
            <tbody>
                {% for rol_nombre in roles_disponibles %}
                <tr>
                    <td>{{ rol_nombre }}</td>
                    <td><input type="checkbox" name="roles" value="{{ rol_nombre }}"></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-success">Agregar Roles</button>
        <a href="{% url 'administracion:gestion_usuarios' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/administracion/crear_categoria.html
{% extends 'base.html' %}
{% block content %}
<style>
    .container {
        max-width: 500px;
        margin: 0 auto;
        /* Centra el contenido horizontalmente */
        padding: 20px;
    }
</style>
<div class="container">
    <h1>Crear Nueva Categoría</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Crear</button>
        <a href="{% url 'administracion:gestion_categorias' %}" class="btn btn-secondary">Cancelar</a>
    </form>

    
</div>
{% endblock %}

templates/administracion/crear_rol.html
{% extends 'base.html' %}

{% block content %}
<style>
.container {
    max-width: 1000px;
    /* Establece el ancho máximo que desees */
    margin: 0 auto;
    /* Centra el contenido horizontalmente */
    padding: 20px;
}
</style>
<div class="container">
    <h1>Crear Nuevo Rol</h1>
    <form method="post" action="{% url 'administracion:crear_rol' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Crear</button>
        <a href="{% url 'administracion:gestion_usuarios' %}" class="btn btn-secondary">Cancelar</a>
    </form>

{% endblock %}

templates/administracion/editar_categoria.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .container {
        max-width: 500px;
        margin: 0 auto;
        /* Centra el contenido horizontalmente */
        padding: 20px;
    }
</style>

<div class="container">
    <br>
    <h1>Editar Categoría</h1>
    <br><br>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br><br>
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        <a href="{% url 'administracion:gestion_categorias' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/administracion/eliminar_categoria.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Eliminar Categoría</h1>

    <p>¿Estás seguro que deseas eliminar la categoría "{{ categoria.nombre }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'administracion:gestion_categorias' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/administracion/eliminar_permisos_roles_usuario.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Eliminar Permisos de Roles del Usuario</h1>

    <form method="post">
        {% csrf_token %}
        <h2>{{ usuario.username }}</h2>

        {% if roles_usuario %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Rol</th>
                    <th>Permisos</th>
                </tr>
            </thead>
            <tbody>
                {% for rol in roles_usuario %}
                <tr>
                    <td>{{ rol.nombre }}</td>
                    <td>
                        {% for permiso in rol.permisos.all %}
                        <label class="form-check-label">
                            <input type="checkbox" name="permisos" value="{{ permiso.id }}"
                                {% if permisos_seleccionados and permiso in permisos_seleccionados %} checked {% endif %}>
                            {{ permiso.name }}
                        </label><br>
                        {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>El usuario no tiene roles asignados.</p>
        {% endif %}
        
        <button type="submit" class="btn btn-danger">Eliminar Permisos</button>
        <a href="{% url 'administracion:gestion_usuarios' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/administracion/eliminar_roles_usuario.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Eliminar Roles de {{ usuario.username }}</h1>

    <form method="post" action="{% url 'administracion:eliminar_roles_usuario' usuario.id %}">
        {% csrf_token %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Rol</th>
                    <th>Seleccionar</th>
                </tr>
            </thead>
            <tbody>
                {% for rol in roles_asignados %}
                <tr>
                    <td>{{ rol.nombre }}</td>
                    <td><input type="checkbox" name="roles" value="{{ rol.id }}"></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-danger">Eliminar Roles</button>
        <a href="{% url 'administracion:gestion_usuarios' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/administracion/eliminar_usuario.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Eliminar Usuario</h1>

    <p>¿Estás seguro de que deseas eliminar al usuario "{{ usuario }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'administracion:gestion_usuarios' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/administracion/gestion_categorias.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link href="{% static 'css/gestion.css' %}" rel="stylesheet" />

<style>
    .limite {
        max-width: 200px;
    }
</style>
<div class="container">
    <br>
    <h1>Gestión de Categorías</h1>
    <br>
    <a href="{% url 'administracion:crear_categoria' %}" class="btn btn-primary">Crear Categoría</a>
    <br><br>
    {% if categorias %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Moderada</th>
                <th>Para Suscriptores</th>
            </tr>
        </thead>
        <tbody>
            {% for categoria in categorias %}
            <tr>
                <td>{{ categoria.nombre }}</td>
                <td>{{ categoria.moderada }}</td>
                <td>{{ categoria.suscriptores }}</td>
                <td>
            </tr>
            <tr>
                <td>
                    <div class="limite">
                        <nav class="custom-nav">
                            <a href="{% url 'administracion:editar_categoria' categoria.id %}"
                                class="custom-nav-item">Editar</a>
                            <a href="{% url 'administracion:eliminar_categoria' categoria.id %}"
                                class="custom-nav-item">Eliminar</a>
                        </nav>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No hay categorías disponibles.</p>
    {% endif %}
    <a href="{% url 'administracion:panel' %}" class="boton-principal">Volver al panel</a>
</div>
{% endblock %}

templates/administracion/gestion_usuarios.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link href="{% static 'css/gestion.css' %}" rel="stylesheet" />

<div class="container">
    <br>
    <h1>Gestión de Usuarios</h1>
    <br>
    <a href="{% url 'administracion:crear_rol'%}" class="btn btn-primary">Crear Rol</a>
    <br><br>
    {% if usuarios %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nombre de Usuario</th>
                <th>Correo Electrónico</th>
                <th>Roles</th>
            </tr>
        </thead>
        <tbody>
            {% for usuario in usuarios %}
            <tr>
                <td>{{ usuario.username }}</td>
                <td>{{ usuario.email }}</td>
                <td>
                    {% for rol in usuario.roles.all %}
                    {{ rol.nombre }}
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <div>
                        <nav class="custom-nav">
                            <a href="{% url 'administracion:eliminar_usuario' usuario.id %}"
                                class="custom-nav-item">Eliminar Usuario</a>
                            <a href="{% url 'administracion:asignar_roles_usuario' usuario.id %}"
                                class="custom-nav-item">Asignar Roles</a>
                            <a href="{% url 'administracion:eliminar_roles_usuario' usuario.id %}"
                                class="custom-nav-item">Eliminar Roles</a>
                            <a href="{% url 'administracion:agregar_permisos_roles_usuario' usuario.id %}"
                                class="custom-nav-item">Agregar Permisos</a>
                            <a href="{% url 'administracion:eliminar_permisos_roles_usuario' usuario.id %}"
                                class="custom-nav-item">Eliminar Permisos</a>
                        </nav>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No hay usuarios disponibles.</p>
    {% endif %}
    <a href="{% url 'administracion:panel' %}" class="boton-principal">Volver al panel</a>
</div>

{% endblock %}

templates/administracion/panel.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Administracion{% endblock %}
{% block content %}
<link href="{% static 'css/panel.css' %}" rel="stylesheet" />
<div class="admin-panel">
  <h1>Panel de Administración</h1>
  <div>
    <a class="custom-nav custom-nav-item" href="{% url 'administracion:gestion_categorias' %}">Gestión de Categorías</a>
    <a class="custom-nav custom-nav-item" href="{% url 'administracion:gestion_usuarios' %}">Gestión de Usuarios</a>
    <!-- Enlace a Google Analytics -->
    <a class="custom-nav custom-nav-item" href="https://analytics.google.com/analytics/web/?pli=1#/p417224859/reports/intelligenthome?params=_u..nav%3Dmaui" target="_blank">Reportes-Google Analytics</a>
  </div>
</div>
{% endblock %}